# Pandas

In [1]:
import pandas as pd

In [2]:
tab = pd.read_csv("pokemon.csv")

In [3]:
tab

,id,name,height,weight,color,shape,is baby,type 1,type 2,hp,attack,defense,speed
0,1,bulbasaur,0.7,6.9,green,quadruped,False,Grass,Poison,45,49,49,45
1,2,ivysaur,1.0,13.0,green,quadruped,False,Grass,Poison,60,62,63,60
2,3,venusaur,2.0,100.0,green,quadruped,False,Grass,Poison,80,82,83,80
3,4,charmander,0.6,8.5,red,upright,False,Fire,NaN,39,52,43,65
4,5,charmeleon,1.1,19.0,red,upright,False,Fire,NaN,58,64,58,80
...,...,...,...,...,...,...,...,...,...,...,...,...,...
802,803,poipole,0.6,1.8,purple,upright,False,Poison,NaN,67,73,67,73
803,804,naganadel,3.6,150.0,purple,wings,False,Poison,Dragon,73,73,73,121
804,805,stakataka,5.5,820.0,gray,quadruped,False,Rock,Steel,61,131,211,13
805,806,blacephalon,1.8,13.0,white,humanoid,False,Fire,Ghost,53,127,53,107
806,807,zeraora,1.5,44.5,yellow,humanoid,False,Electric,NaN,88,112,75,143

In [4]:
deti = tab["is baby"]
deti

0      False
1      False
2      False
3      False
4      False
       ...
802    False
803    False
804    False
805    False
806    False
Name: is baby, Length: 807, dtype: bool

In [5]:
deti.name

'is baby'

In [6]:
tab.index

RangeIndex(start=0, stop=807, step=1)

In [9]:
pok = tab.set_index("is baby").sort_index(ascending = False);
pok

,id,name,height,weight,color,shape,type 1,type 2,hp,attack,defense,speed
is baby,,,,,,,,,,,,
True,440,happiny,0.6,24.4,pink,humanoid,Normal,NaN,100,5,5,30
True,458,mantyke,1.0,65.0,blue,wings,Water,Flying,45,20,50,50
True,238,smoochum,0.4,6.0,pink,humanoid,Ice,Psychic,45,30,15,65
True,239,elekid,0.6,23.5,yellow,humanoid,Electric,NaN,45,63,37,95
True,439,mime-jr,0.6,13.0,pink,humanoid,Psychic,Fairy,20,25,45,60
...,...,...,...,...,...,...,...,...,...,...,...,...
False,276,taillow,0.3,2.3,blue,wings,Normal,Flying,40,55,30,85
False,277,swellow,0.7,19.8,blue,wings,Normal,Flying,60,85,60,125
False,278,wingull,0.6,9.5,white,wings,Water,Flying,40,30,30,85
False,279,pelipper,1.2,28.0,yellow,wings,Water,Flying,60,50,100,65
False,807,zeraora,1.5,44.5,yellow,humanoid,Electric,NaN,88,112,75,143

In [12]:
jendeti = pok.filter(like="True", axis=0)
jendeti

,id,name,height,weight,color,shape,type 1,type 2,hp,attack,defense,speed
is baby,,,,,,,,,,,,
True,440,happiny,0.6,24.4,pink,humanoid,Normal,NaN,100,5,5,30
True,458,mantyke,1.0,65.0,blue,wings,Water,Flying,45,20,50,50
True,238,smoochum,0.4,6.0,pink,humanoid,Ice,Psychic,45,30,15,65
True,239,elekid,0.6,23.5,yellow,humanoid,Electric,NaN,45,63,37,95
True,439,mime-jr,0.6,13.0,pink,humanoid,Psychic,Fairy,20,25,45,60
True,438,bonsly,0.5,15.0,brown,legs,Rock,NaN,50,80,95,10
True,446,munchlax,0.6,105.0,black,humanoid,Normal,NaN,135,85,40,5
True,447,riolu,0.7,20.2,blue,upright,Fighting,NaN,40,70,40,60
True,175,togepi,0.3,1.5,white,humanoid,Fairy,NaN,35,20,65,20
True,174,igglybuff,0.3,1.0,pink,humanoid,Normal,Fairy,90,30,15,15
True,433,chingling,0.2,0.6,yellow,humanoid,Psychic,NaN,45,30,50,45
True,173,cleffa,0.3,3.0,pink,upright,Fairy,NaN,50,25,28,15
True,172,pichu,0.3,2.0,yellow,quadruped,Electric,NaN,20,40,15,60
True,240,magby,0.7,21.4,red,upright,Fire,NaN,45,75,37,83
True,236,tyrogue,0.7,21.0,purple,humanoid,Fighting,NaN,35,35,35,35
True,360,wynaut,0.6,14.0,blue,upright,Psychic,NaN,95,23,48,23
True,406,budew,0.2,1.2,green,humanoid,Grass,Poison,40,30,35,55
True,298,azurill,0.2,2.0,blue,legs,Normal,Fairy,50,20,40,20